name: Deploy with Config

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Generate config file
        run: |
          echo "window.config = { API_KEY: '${{ secrets.NEETS_API_KEY }}' };" > config.js
      
      - name: Prepare deployment
        run: |
          mkdir -p ./dist
          cp index.html ./dist/
          cp config.js ./dist/
          ls -la ./dist
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true